language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly
  - hhvm

install:
  - travis_retry composer install --no-interaction --prefer-source

before_install:
  - if [[ $PHP_VERSION == nightly ]]; then echo "Installing php-coveralls for nightly build"; composer require php-coveralls/php-coveralls --no-interaction --prefer-source; fi

script:
  - if [[ $PHP_VERSION != nightly && $PHP_VERSION != hhvm ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [[ $PHP_VERSION == nightly || $PHP_VERSION == hhvm ]]; then vendor/bin/phpunit --coverage-text; fi
  - vendor/bin/phpcs --standard=phpcs.xml src

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

  fast_finish: true

after_success:
  - if [[ $PHP_VERSION != nightly && $PHP_VERSION != hhvm ]]; then travis_retry php vendor/bin/php-coveralls; fi
