# frozen_string_literal: true

source 'https://rubygems.org' do
  # Use the latest compatible version of Jekyll and its plugins
  gem 'jekyll', '>= 3.7.0'
  gem 'jekyll-redirect-from', '>= 0.13.0'
  gem 'jekyll-sitemap', '>= 1.1.1'
  gem 'jekyll-toc', '>= 0.5.1'
end

# Exclude development and test dependencies from the production environment
group :development, :test do
  gem 'web-console'
  gem 'spring'
  gem 'spring-watcher-listen'
end
